# Day 7: Pandas Essentials — DataFrames and Data Manipulation

Welcome to **Day 7 of your Data Science Journey**! Today, we transition to **Pandas** (Python Data Analysis Library), the standard Python package used to load, clean, analyze, and transform tabular datasets.

## What is Pandas?
Pandas is an open-source Python library that provides high-performance, easy-to-use data structures and data analysis tools. It is built on top of NumPy, meaning it inherits NumPy's speed while adding indexable rows and columns.

### Why do we need Pandas in Data Science?
Standard Python lists and dictionaries are highly flexible but slow for doing heavy data calculations. NumPy arrays are extremely fast but can only hold a single data type (homogeneous) and lack labeled columns or rows. 

Pandas combines the best of both worlds: it handles tables of mixed data types (heterogeneous) and allows us to reference columns by name and rows by indices.

| Feature | Python Lists / Dicts | NumPy Arrays | Pandas DataFrames / Series |
| :--- | :--- | :--- | :--- |
| **Structure** | Unstructured or Nested | Homogeneous N-D Array | Heterogeneous Tabular 2D Grid / 1D Columns |
| **Row/Col Labels** | Index only / Dict keys | Numeric index only | Custom Index & Column Labels |
| **Data Types** | Mixed (slow) | Homogeneous (fast) | Mixed per column (fast, built on NumPy) |
| **Missing Data** | `None` (manual check) | `nan` (limited support) | `NaN` / `None` (built-in automatic alignment & handling) |

### 🧠 Data Structures Visual representation:
```text
Pandas Series (1D column with index):
       Index    Values
         0  ──►  23
         1  ──►  45
         2  ──►  31

Pandas DataFrame (2D table made of aligned Series columns):
       Index      Name      Age     Income
         0   ──►  Alice     23      50000
         1   ──►  Bob       45      85000
         2   ──►  Charlie   31      62000
```

Let's start by installing and importing Pandas!

In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\swastik\desktop\training\aiml\.venv\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\swastik\desktop\training\aiml\.venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\swastik\desktop\training\aiml\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\swastik\desktop\training\aiml\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\swastik\desktop\training\aiml\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\Users\swastik\Desktop\training\aiml\.venv\Scripts\python.exe -m pip install --upgrade pip

In [ ]:
%pip install pandas

---

## Module 1: Pandas Data Structures (Series & DataFrames)

The two primary structures in Pandas are the **`Series`** (1-dimensional) and the **`DataFrame`** (2-dimensional). 

- **Series**: A one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.).
- **DataFrame**: A two-dimensional labeled data structure with columns of potentially different types, like a spreadsheet or SQL table.

In [ ]:
%pip install pandas

In [3]:
import numpy as np
import pandas as pd

In [10]:
list1=[10,20,30,40]
print(list1)
arr=np.array(list1)

series1=pd.Series(list1,name="Age")
print(series1)
print(type(series1))

[10, 20, 30, 40]
0    10
1    20
2    30
3    40
Name: Age, dtype: int64
<class 'pandas.Series'>

In [2]:
arr1=np.array([10,20,30,40])
print(arr1)

series1=pd.Series([10,20,30,40],name="Ages")
print(series1)
print(type(series1))

[10 20 30 40]
0    10
1    20
2    30
3    40
Name: Ages, dtype: int64
<class 'pandas.Series'>

In [12]:
student={"Name":["sima","ria","ryan"],
         "course":["BCA","btech","BCA"],
         "Rollno":[1,2,3]}

df=pd.DataFrame(student)
df
df.shape

(3, 3)

In [3]:
# 1. Creating a Series from a list
ages = pd.Series([23, 45, 31, 19], name="Age")
print("Pandas Series:\n", ages)
print("Type of ages: ", type(ages))

# 2. Creating a DataFrame manually from a dictionary of lists
manual_df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [23, 45, 31, 19],
    "Income": [50000, 85000, 62000, 22000]
})
print("\nManually Created DataFrame:\n", manual_df)
print("\nDataFrame Shape (rows, columns):", manual_df.shape)

Pandas Series:
 0    23
1    45
2    31
3    19
Name: Age, dtype: int64
Type of ages:  <class 'pandas.Series'>

Manually Created DataFrame:
       Name  Age  Income
0    Alice   23   50000
1      Bob   45   85000
2  Charlie   31   62000
3    David   19   22000

DataFrame Shape (rows, columns): (4, 3)

---

## Module 2: Reading Data & Dataset Inspection

Usually, datasets are loaded from external files (like CSV or Excel). We use **`pd.read_csv()`** to load CSV files.

Here, we will mock a CSV file using python's `io.StringIO` to simulate file loading without external file dependencies.

In [18]:
df=pd.read_csv("data.csv")

In [19]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103   NaN      F  62000.0       Yes
3         104  31.0      M      NaN        No
4         105  19.0      F  22000.0        No
5         106  52.0    NaN  98000.0       Yes

In [20]:
df.dtypes

CustomerID      int64
Age           float64
Gender            str
Income        float64
Purchased         str
dtype: object

In [21]:
df.shape

(6, 5)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  6 non-null      int64
 1   Age         5 non-null      float64
 2   Gender      5 non-null      str
 3   Income      5 non-null      float64
 4   Purchased   6 non-null      str
dtypes: float64(2), int64(1), str(2)
memory usage: 372.0 bytes

In [23]:
df.head(2)

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes

In [24]:
df.tail(3)

   CustomerID   Age Gender   Income Purchased
3         104  31.0      M      NaN        No
4         105  19.0      F  22000.0        No
5         106  52.0    NaN  98000.0       Yes

In [25]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Income', 'Purchased'], dtype='str')

In [77]:
df.columns.to_list()

['CustomerID', 'Age', 'Gender', 'Income', 'Purchased']

In [78]:
df.describe()

       CustomerID       Age        Income
count    5.000000   5.00000      5.000000
mean   103.000000  31.36000  54750.000000
std      1.581139  10.60415  22708.753819
min    101.000000  19.00000  22000.000000
25%    102.000000  25.00000  50000.000000
50%    103.000000  31.00000  54750.000000
75%    104.000000  34.80000  62000.000000
max    105.000000  47.00000  85000.000000

In [28]:
import io
# Mock csv file content representing customer records
csv_data = """CustomerID,Age,Gender,Income,Purchased
101,25,F,50000.0,No
102,47,M,85000.0,Yes
103,,F,62000.0,Yes
104,31,M,,No
105,19,F,22000.0,No
106,52,,98000.0,Yes
"""
#for vs code
df=pd.read_csv("data.csv")
# Load string data into a Pandas DataFrame
import io
df = pd.read_csv(io.StringIO(csv_data))

# 1. View first few records (default is 5, let's view 3)
print("--- head() (First 3 rows) ---")
print(df.head(3))

# 2. Inspect shape & schema details (essential to find missing Nulls)
print("\n--- info() ---")
df.info()

# 3. Statistical summary (means, min, max, standard deviations)
print("\n--- describe() ---")
print(df.describe())

--- head() (First 3 rows) ---
   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103   NaN      F  62000.0       Yes

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  6 non-null      int64
 1   Age         5 non-null      float64
 2   Gender      5 non-null      str
 3   Income      5 non-null      float64
 4   Purchased   6 non-null      str
dtypes: float64(2), int64(1), str(2)
memory usage: 372.0 bytes

--- describe() ---
       CustomerID        Age        Income
count    6.000000   5.000000      5.000000
mean   103.500000  34.800000  63400.000000
std      1.870829  14.184499  29829.515584
min    101.000000  19.000000  22000.000000
25%    102.250000  25.000000  50000.000000
50%    103.500000  31.000000  62000.000000
75%    104.750000  47.000000  85000.000000
max    106.000000  52.000000  98000.000000

In [29]:
import pandas as pd

In [30]:
df=pd.read_csv("data.csv")

In [31]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103   NaN      F  62000.0       Yes
3         104  31.0      M      NaN        No
4         105  19.0      F  22000.0        No
5         106  52.0    NaN  98000.0       Yes

In [32]:
df.index.to_list()

[0, 1, 2, 3, 4, 5]

In [33]:
# Inspecting individual attributes of a DataFrame
print("Shape (rows, cols): ", df.shape)
print("Columns:           ", df.columns.tolist())
print("Indices:           ", df.index.tolist())
print("\nData Types:\n", df.dtypes)

Shape (rows, cols):  (6, 5)
Columns:            ['CustomerID', 'Age', 'Gender', 'Income', 'Purchased']
Indices:            [0, 1, 2, 3, 4, 5]

Data Types:
 CustomerID      int64
Age           float64
Gender            str
Income        float64
Purchased         str
dtype: object

---

## Module 3: Slicing & Selecting Data

Extracting subsets of columns and rows is standard practice.
- **Column Selection**: Select columns using brackets `df['col_name']` or a list of columns `df[['col1', 'col2']]`.
- **Positional Slicing (`.iloc`)**: Select rows and columns by integer index position `.iloc[row_idx, col_idx]`.
- **Label-based Indexing (`.loc`)**: Select rows and columns by labels `.loc[row_label, col_label]`.

In [80]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103  34.8      F  62000.0       Yes
3         104  31.0      M  54750.0        No
4         105  19.0      F  22000.0        No

In [81]:
df["CustomerID":"Age"]

TypeError: cannot do slice indexing on RangeIndex with these indexers [CustomerID] of type str

In [83]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Income', 'Purchased'], dtype='str')

In [82]:
cols=["CustomerID","Age","Income"]
df[cols]

   CustomerID   Age   Income
0         101  25.0  50000.0
1         102  47.0  85000.0
2         103  34.8  62000.0
3         104  31.0  54750.0
4         105  19.0  22000.0

In [36]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103   NaN      F  62000.0       Yes
3         104  31.0      M      NaN        No
4         105  19.0      F  22000.0        No
5         106  52.0    NaN  98000.0       Yes

In [86]:
df.loc[0:3,"CustomerID":"Income"]

   CustomerID   Age Gender   Income
0         101  25.0      F  50000.0
1         102  47.0      M  85000.0
2         103  34.8      F  62000.0
3         104  31.0      M  54750.0

In [88]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103  34.8      F  62000.0       Yes
3         104  31.0      M  54750.0        No
4         105  19.0      F  22000.0        No

In [87]:
cols=["CustomerID","Income"]
df.loc[0:3,cols]

   CustomerID   Income
0         101  50000.0
1         102  85000.0
2         103  62000.0
3         104  54750.0

In [38]:
df.iloc[1:4,1:4]

    Age Gender   Income
1  47.0      M  85000.0
2   NaN      F  62000.0
3  31.0      M      NaN

In [ ]:
cols=["Age","Purchased"]
row_record = df.loc[1:4, cols]
row_record

    Age Purchased
1  47.0       Yes
2   NaN       Yes
3  31.0        No
4  19.0        No

In [40]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103   NaN      F  62000.0       Yes
3         104  31.0      M      NaN        No
4         105  19.0      F  22000.0        No
5         106  52.0    NaN  98000.0       Yes

In [90]:
df["Income"]>50000
df[df["Income"]>50000]

   CustomerID   Age Gender   Income Purchased
1         102  47.0      M  85000.0       Yes
2         103  34.8      F  62000.0       Yes
3         104  31.0      M  54750.0        No

In [41]:
df["Income"]>60000
df[df["Income"]>60000]

   CustomerID   Age Gender   Income Purchased
1         102  47.0      M  85000.0       Yes
2         103   NaN      F  62000.0       Yes
5         106  52.0    NaN  98000.0       Yes

In [42]:
df[df["Income"]>60000.0]

   CustomerID   Age Gender   Income Purchased
1         102  47.0      M  85000.0       Yes
2         103   NaN      F  62000.0       Yes
5         106  52.0    NaN  98000.0       Yes

In [43]:
df.dtypes

CustomerID      int64
Age           float64
Gender            str
Income        float64
Purchased         str
dtype: object

In [44]:
df.dtypes

CustomerID      int64
Age           float64
Gender            str
Income        float64
Purchased         str
dtype: object

In [45]:
df["Income"].astype("float64")

0    50000.0
1    85000.0
2    62000.0
3        NaN
4    22000.0
5    98000.0
Name: Income, dtype: float64

In [46]:
df[df["Age"]>25]

   CustomerID   Age Gender   Income Purchased
1         102  47.0      M  85000.0       Yes
3         104  31.0      M      NaN        No
5         106  52.0    NaN  98000.0       Yes

In [47]:
# 1. Column Selection
income_col = df["Income"]  # Returns a 1D Series
print("Type of single column selection:", type(income_col))

features_df = df[["Age", "Income"]]  # Returns a 2D DataFrame
print("\nMultiple columns DataFrame:\n", features_df)

# 2. Selecting slices using .iloc[rows, columns]
# Select rows 1 to 3 (index positions 1, 2, 3), and columns index 1 to 3 (Age and Gender)
slice_df = df.iloc[1:4, 1:4]
print("\nPositional slice (iloc):\n", slice_df)

# 3. Selecting using .loc (label-based)
# Select the value at row label 1, column name 'Age'
row_record = df.loc[1, "Age"]
print(f"\nValue at row label 1, column 'Age': {row_record}")

Type of single column selection: <class 'pandas.Series'>

Multiple columns DataFrame:
     Age   Income
0  25.0  50000.0
1  47.0  85000.0
2   NaN  62000.0
3  31.0      NaN
4  19.0  22000.0
5  52.0  98000.0

Positional slice (iloc):
     Age Gender   Income
1  47.0      M  85000.0
2   NaN      F  62000.0
3  31.0      M      NaN

Value at row label 1, column 'Age': 47.0

---

## Module 4: Boolean Indexing: Filtering Rows

In Machine Learning, we often filter records based on specific criteria (e.g. selecting rows where income is above a threshold).
- Wrap conditions in parentheses.
- Use bitwise operators: `&` for **AND**, `|` for **OR**, `~` for **NOT**.

In [48]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103   NaN      F  62000.0       Yes
3         104  31.0      M      NaN        No
4         105  19.0      F  22000.0        No
5         106  52.0    NaN  98000.0       Yes

In [49]:
df[(df["Age"] >= 25) & (df["Gender"] == "F")]

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No

In [50]:
# 1. Create a boolean mask (evaluation list of True/False)
mask = df["Income"] > 60000.0
print("Boolean Mask:\n", mask)

# 2. Apply mask to filter DataFrame rows
high_earners = df[mask]
print("\nFiltered high earners:\n", high_earners)

# 3. Combining multiple conditions using & (AND)
# Select female customers with an income greater than 40k
target_users = df[(df["Income"] > 40000) & (df["Gender"] == "F")]
print("\nFemales with income > 40k:\n", target_users)

Boolean Mask:
 0    False
1     True
2     True
3    False
4    False
5     True
Name: Income, dtype: bool

Filtered high earners:
    CustomerID   Age Gender   Income Purchased
1         102  47.0      M  85000.0       Yes
2         103   NaN      F  62000.0       Yes
5         106  52.0    NaN  98000.0       Yes

Females with income > 40k:
    CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
2         103   NaN      F  62000.0       Yes

In [51]:
import pandas as pd
df=pd.read_csv("data.csv")

In [52]:
df.isnull().sum()

CustomerID    0
Age           1
Gender        1
Income        1
Purchased     0
dtype: int64

In [53]:
mean=df["Age"].mean()
mean
df["Age"]=df["Age"].fillna(mean)

In [54]:
df.isnull().sum()

CustomerID    0
Age           0
Gender        1
Income        1
Purchased     0
dtype: int64

In [55]:
mean=df["Age"].mean()
df["Age"]=df["Age"].fillna(mean)
print(mean)

34.800000000000004

In [56]:
df=df.dropna(subset=["Gender"])

In [57]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103  34.8      F  62000.0       Yes
3         104  31.0      M      NaN        No
4         105  19.0      F  22000.0        No

In [58]:
mean=df["Income"].mean()
df["Income"]=df["Income"].fillna(mean)
print(mean)
print(df.isnull().sum())

54750.0
CustomerID    0
Age           0
Gender        0
Income        0
Purchased     0
dtype: int64

---

## Module 5: Cleaning Missing Data (NaNs)

Real-world datasets contain gaps (represented as `NaN` — Not a Number). Machine Learning models cannot be trained with missing inputs. We must handle them:
1. **Detecting Nulls**: Check null value counts per column using `.isnull().sum()`.
2. **Strategy A (Imputation)**: Fill NaNs using `.fillna()`.
3. **Strategy B (Deletion)**: Remove rows containing NaNs using `.dropna()`.

In [59]:
# 1. Count missing values per column
print("Missing values counts:\n", df.isnull().sum())

# 2. Strategy A: Fill NaNs (Imputation)
# Fill missing Income values with the mean of the column
income_mean = df["Income"].mean()
df_filled = df.copy()
df_filled["Income"] = df_filled["Income"].fillna(income_mean)
print(f"\nIncome filled with mean ({income_mean:.2f}):\n", df_filled)

# 3. Strategy B: Drop NaNs (Deletion)
# Drops any row that contains any missing value
df_dropped = df.dropna()
print("\nDataFrame after dropping any NaN row:\n", df_dropped)

Missing values counts:
 CustomerID    0
Age           0
Gender        0
Income        0
Purchased     0
dtype: int64

Income filled with mean (54750.00):
    CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103  34.8      F  62000.0       Yes
3         104  31.0      M  54750.0        No
4         105  19.0      F  22000.0        No

DataFrame after dropping any NaN row:
    CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103  34.8      F  62000.0       Yes
3         104  31.0      M  54750.0        No
4         105  19.0      F  22000.0        No

In [60]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103  34.8      F  62000.0       Yes
3         104  31.0      M  54750.0        No
4         105  19.0      F  22000.0        No

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  5 non-null      int64
 1   Age         5 non-null      float64
 2   Gender      5 non-null      str
 3   Income      5 non-null      float64
 4   Purchased   5 non-null      str
dtypes: float64(2), int64(1), str(2)
memory usage: 332.0 bytes

---

## Module 6: Groupby & Aggregations

Analyzing stats by grouping categories is essential (e.g. comparing average income of customers who purchased vs those who didn't). We use **`.groupby()`** followed by an aggregation function like `.mean()`, `.sum()`, `.count()`.

In [62]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103  34.8      F  62000.0       Yes
3         104  31.0      M  54750.0        No
4         105  19.0      F  22000.0        No

In [63]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103  34.8      F  62000.0       Yes
3         104  31.0      M  54750.0        No
4         105  19.0      F  22000.0        No

In [64]:
cols=["Income","Age"]
df.groupby("Gender")[cols].mean()

              Income        Age
Gender
F       44666.666667  26.266667
M       69875.000000  39.000000

In [65]:
df

   CustomerID   Age Gender   Income Purchased
0         101  25.0      F  50000.0        No
1         102  47.0      M  85000.0       Yes
2         103  34.8      F  62000.0       Yes
3         104  31.0      M  54750.0        No
4         105  19.0      F  22000.0        No

In [66]:
cols=["Income","Age"]
df.groupby("Purchased")[cols].mean()

            Income   Age
Purchased
No         42250.0  25.0
Yes        73500.0  40.9

In [67]:
# Group by 'Purchased' column and calculate the mean of numerical columns
# We explicitly select numeric columns to avoid warnings/errors with newer pandas versions
numeric_cols = ["Age", "Income"]
grouped_means = df_filled.groupby("Purchased")[numeric_cols].mean()
print("Averages grouped by Purchase status:\n", grouped_means)

# We can target specific columns for grouping summary 
avg_income_grouped = df_filled.groupby("Purchased")["Income"].mean()
print("\nAverage Income by purchase group:\n", avg_income_grouped)

Averages grouped by Purchase status:
             Age   Income
Purchased
No         25.0  42250.0
Yes        40.9  73500.0

Average Income by purchase group:
 Purchased
No     42250.0
Yes    73500.0
Name: Income, dtype: float64

---

## Module 7: Hands-On Practice Exercises!

Use the student evaluation dataset to test your Pandas essentials skills. Solve each exercise in the cell provided.

### Exercise 1: Dataset Loading & Inspection
You have a mock CSV string representing student evaluations.
1. Load the CSV text into a Pandas DataFrame `eval_df`.
2. Display the first 4 rows of the dataset.
3. Print out the count of null values in each column.

In [68]:
student_csv = """StudentID,HoursStudied,Grade,Passed,Attendance
201,15.5,88,Yes,95.0
202,8.0,62,No,88.0
203,,75,Yes,90.0
204,12.0,,Yes,79.0
205,5.5,45,No,
206,18.0,95,Yes,98.0
"""

# Write your dataset inspection code here:

### Exercise 2: Selecting Columns & Boolean Filtering
Using the `eval_df` loaded in Exercise 1:
1. Filter rows where `Passed` is equal to `"Yes"`.
2. Extract only the columns `HoursStudied` and `Grade` from this filtered subset.
3. Save this result in variable `passed_grades` and print it.

In [69]:
# Write your selection and filtering code here:

### Exercise 3: Null Values Cleaning
AI models cannot train with missing values. Clean `eval_df`:
1. Compute the mean of the `HoursStudied` column.
2. Fill the missing values in `HoursStudied` with this mean.
3. Since `Grade` is our target prediction, we shouldn't guess/impute it. Drop any rows that still have a missing value in the `Grade` column.
4. Save the cleaned dataset as `clean_eval_df` and display it.

In [70]:
# Write your NaN cleaning code here:

### Exercise 4: Groupby Summary Statistics
Using `clean_eval_df` from Exercise 3:
1. Group the dataset by the `Passed` status column.
2. Find the average `HoursStudied`, `Grade`, and `Attendance` for the groups.
3. Print this aggregated summary.

In [71]:
# Write your grouping and aggregation code here:

--- 

## Solutions (Double click to reveal & check!)

Below are the verified solutions for each of the exercises. Double click the cells to view the code, and run them to verify your solutions.

### Exercise 1 Solution

In [72]:
eval_df = pd.read_csv(io.StringIO(student_csv))

print("First 4 rows:\n", eval_df.head(4))
print("\nMissing values count:\n", eval_df.isnull().sum())

First 4 rows:
    StudentID  HoursStudied  Grade Passed  Attendance
0        201          15.5   88.0    Yes        95.0
1        202           8.0   62.0     No        88.0
2        203           NaN   75.0    Yes        90.0
3        204          12.0    NaN    Yes        79.0

Missing values count:
 StudentID       0
HoursStudied    1
Grade           1
Passed          0
Attendance      1
dtype: int64

### Exercise 2 Solution

In [73]:
passed_grades = eval_df[eval_df["Passed"] == "Yes"][["HoursStudied", "Grade"]]
print("Passed student grades:\n", passed_grades)

Passed student grades:
    HoursStudied  Grade
0          15.5   88.0
2           NaN   75.0
3          12.0    NaN
5          18.0   95.0

### Exercise 3 Solution

In [74]:
mean_hours = eval_df["HoursStudied"].mean()

# Fill missing hours
clean_eval_df = eval_df.copy()
clean_eval_df["HoursStudied"] = clean_eval_df["HoursStudied"].fillna(mean_hours)

# Drop remaining rows missing Grade
clean_eval_df = clean_eval_df.dropna(subset=["Grade"])

print("Cleaned DataFrame:\n", clean_eval_df)

Cleaned DataFrame:
    StudentID  HoursStudied  Grade Passed  Attendance
0        201          15.5   88.0    Yes        95.0
1        202           8.0   62.0     No        88.0
2        203          11.8   75.0    Yes        90.0
4        205           5.5   45.0     No         NaN
5        206          18.0   95.0    Yes        98.0

### Exercise 4 Solution

In [75]:
grouped_summary = clean_eval_df.groupby("Passed")[["HoursStudied", "Grade", "Attendance"]].mean()
print("Grouped Averages:\n", grouped_summary)

Grouped Averages:
         HoursStudied  Grade  Attendance
Passed
No              6.75   53.5   88.000000
Yes            15.10   86.0   94.333333

---
**Incredible work!** You have completed the Pandas foundations module. You are now fully prepared to clean datasets, extract features, and group summaries, which are the primary skills needed for any data scientist and machine learning practitioner.

Make sure to open your terminal and run `python day7_visualizer.py` to play the **Interactive 3D Pandas DataFrames Simulation**!